### ISSUE TITLE
Miscellaneous documentation issues

### ISSUE THREAD

**Issue by rabernat** [pangeo-forge/pangeo-forge-recipes#302]
- [x] [What is pangeo forge?](https://pangeo-forge.readthedocs.io/en/latest/what_is_pangeo_forge.html) page is superficial and short - @rabernat - fixed in #311 
- [x] Link to intro tutorial on the main index is not active - @rabernat - fixed in #303
- [x] Links to "reference pages" on the main index are not active - should we have standalone API documentation? - @rabernat  - fixed in #303
- [x] Links under "Repository Reference" on the main index are not active - @rabernat 
- [x] Many missing links under [Connecting the Community](https://pangeo-forge.readthedocs.io/en/latest/#connecting-the-community) - @rwegener2 
- [ ] [Cloud automation user guide](https://pangeo-forge.readthedocs.io/en/latest/cloud_automation_user_guide/index.html) is in general very thin - @cisaacstern 
- [ ] [Recipe Box](https://pangeo-forge.readthedocs.io/en/latest/cloud_automation_user_guide/recipe_box.html) description needs significant updates - @cisaacstern

**Comment by rabernat** [comment]
@cisaacstern and @rwegener2  - I have made some tentative assignments in my list above. Do you feel comfortable with that? Ideally we can get this done by Friday before the session.

I am working on my items right now.

**Comment by cisaacstern** [comment]
Yes, happy to handle my two assigned items.

Re: **Recipe Box**, what _is_ this?

We don't keep a Recipes table in the API/database ... and therefore there is no actual **Recipes** page anywhere which maintains a browsable list (or "Box") of recipes.

**Comment by rabernat** [comment]
So maybe we need to update that wording and terminology to align with our current model. We also need to link copiously to the forthcoming dynamic website.
