### ISSUE TITLE
Integrate feedback to intro tutorials

### ISSUE THREAD

**Issue by rwegener2** [pangeo-forge/pangeo-forge-recipes#312]
This fantastic feedback came from Paige. A PR is coming soon to make these changes.
## PART 1
**First page “Introduction Tutorial”**
- [x] it says that you expect folks to have “Pangeo-forge-recipes” installed. Can you add a link?
- [x] More clarity on this page if I am running the tutorial on my local computer, on the Cloud, on a Binder, etc. 
Maybe also specify where you expect folks to run the tutorial from vs. where they should actually work when using Pangeo Forge for real (e.g. use Binder for the demo, but when using Pangeo Forge normally run on your own computer) 
_Status_: (<- add "code won't be saved from sandbox" in the sandbox link PR. Add section discussing local dev vs. sandbox)

**Where should I write this code?**
- [x] Might be nice to include a bit more on why I would choose one over the other. The wording is a bit unclear/vague - is it best to just start with a text editor? Is there a reason Jupyter notebook would be better?

**Explore the structure**
- [x] “By putting the URL into a web browser…”
This is confusing - should I be copy/pasting the above link? The wording just seems to specifically indicate that I shouldn’t click the link, but rather copy/past. Maybe just say “By clicking on the above link, we can explore…”
I like the line “important takeaways are…” :)

**About the FilePattern object**
- [x] Under bullet point 2, the s of “keys” is not pink. There are a couple other places where this is inconsistent as well.

**Define a Format Function**
- [ ] In code block that defines `make_url(time)`
The %d is in pink - is this intentional?
_Status_: This is odd, but I'm not sure how to fix it.  Leaving as is for now.

## PART 2
**Create the Recipe object**
- [x] Typo in last line: 
should be “In more complex recipes additional arguments may get used, but…”
- [x] How do they know that setting `inputs_per_chunk` =10 results in chunks of about size 100MB? Maybe mention how they can check the size of their data, especially if they haven’t downloaded it yet

**Set up logging**
- [x] Could add another sentence of why logging is useful (it’s mentioned that it can be useful, but why? What is being logged?)

**Prune the recipe**
- [x] Typo in first line: “setup” should be “set up”
- [ ] How does `recip.copy_pruned()` decide how long the pruned time dimension is? Is it always 2 time steps? Is `copy_pruned()` kind of equivalent to running e.g. xarray_dataset.isel(time=slice(0,2))?
- [x] Is the `copy_pruned()` function only useful for demos like this? When would I use this in creating a real recipe?

**Run the recipe**
- [x] Typo in second-to-last sentence: “A” should be lower case (within the parentheses)
- [x] Typo in last sentence: “it can be run…”

**Code Summary**
- [x] Typo: should say “code written in part 2”

## General comments
- [x] I think it might be worth reminding the user what the overall goals/outcomes are for the different tutorial sections. Near the end of Part 2, there is a line saying that the time has come to run the recipe, but I realized that I wasn’t sure/forgot what the recipe did and why that was exciting. 
- [x] It seems like there are 2 main aspects of the Pangeo-Forge process: converting data to zarr (or some other ARCO format) and then uploading to the Cloud. In my eyes, it looks like parts 1 and 2 are for converting data to zarr and then part 3 is for adding to cloud. Maybe make that more clear in the first page of the Intro tutorial? (e.g. when outlining the 3 parts) I also know that you have thought about this WAY more than me, so if I’m wrong or what I’ve said doesn’t make sense, just ignore! :)
- [x] Adding an extra sentence about what a FilePattern does on the first page of the Tutorial (the overview page) might also be helpful, or at least at the top of the page for Part 1.
- [x] The text on the overview page of the tutorial appears to essentially be copied over at the top of the pages in parts 1 and 2. This is just fine, but I think having some sort of designation (e.g. a horizontal line) to let the reader know that that is text we have already read would be nice. I found myself starting to read it each time, realizing that I had already read it, but then having to scan around to figure out where the next text for that part of the tutorial starts.
